### ISSUE TITLE
Github Graphql Access

### ISSUE THREAD

**Issue by james-gibson** [gibsunas/lemon-extract#6]
### Tasks
- [ ] Read github token from env
- [ ] Execute a viewer query
- [ ] Store viewer query in lemon context

### Query
```
query { 
  viewer { 
    login
  }
}
```

expected response
```
{
  "data": {
    "viewer": {
      "login": "james-gibson"
    }
  }
}
```
